services:
  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/frontend:latest
    networks:
      - caddy-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
    labels:
      caddy.reverse_proxy: "{{upstreams 80}}"

  api:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/backend:latest
    environment:
      - SECRET_API_KEY=${SECRET_API_KEY}
    networks:
      - caddy-network
      - private
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        order: start-first
    labels:
      caddy.reverse_proxy: "{{upstreams 80}}"